@startuml CG_N2_OpenTK_NAO_Usar_Sequencia

title Diagrama de Sequência - Render Gráfico
footer Grupo GCG - [[http://gcg.inf.furb.br]]

  participant "OnLoad()" as A
  participant "OnUpdateFrame()" as B
  participant "OnRenderFrame()" as C
activate A
  A -> B:  __inicializa
deactivate A
activate B
  B -> C: __desenhar
  activate C
    C --> B: __ajustes
  deactivate B
deactivate C
@enduml
